- name: Netlify Deploy
  # You may pin to the exact commit or the version.
  # uses: jsmrcaga/action-netlify-deploy@53de32e559b0b3833615b9788c7a090cd2fddb03
  uses: jsmrcaga/action-netlify-deploy@v1.8.0
  with:
    # Auth token to use with netlify
    NETLIFY_AUTH_TOKEN: # default is 
    # Your Netlify site id
    NETLIFY_SITE_ID: # default is 
    # Should the site be deployed to production?
    NETLIFY_DEPLOY_TO_PROD: # optional
    # A deploy message
    NETLIFY_DEPLOY_MESSAGE: # optional, default is 
    # Directory where built files are stored
    build_directory: # default is build
    # Directory where built files are stored
    functions_directory: # optional, default is 
    # Command to install dependencies
    install_command: # optional, default is 
    # Command to build static website
    build_command: # optional, default is npm run build
    # Deployment Subdomain name
    deploy_alias: # optional, default is 
    # Node version or arguments compatible with `nvm install`
    node_version: # optional, default is 
    # Enables you to disable nvm altogether
    use_nvm: # optional, default is true
